name: Deploy CentOS Images to DockerHub

on:
  push:
    branches:
      - master
    paths:
      - 'CentOS.Dockerfile'
      - 'entrypoint.sh'
      - '**/deploy-centos-images-to-dockerhub.yml'

jobs:
  centos-6-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish CentOS:6 to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: daniccan/centos-gosu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: CentOS.Dockerfile
        buildargs: OS_VERSION=6
        tags: 6

  centos-7-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish CentOS:7 to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: daniccan/centos-gosu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: CentOS.Dockerfile
        buildargs: OS_VERSION=7
        tags: 7

  centos-8-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish CentOS:8 to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: daniccan/centos-gosu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: CentOS.Dockerfile
        buildargs: OS_VERSION=8
        tags: 8
